"""v2 schemas

Revision ID: 475c2fb19c19
Revises: 7d5477527d5e
Create Date: 2026-07-08 19:51:04.349018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '475c2fb19c19'
down_revision: Union[str, None] = '7d5477527d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibration_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=100), nullable=False),
    sa.Column('confidence_tier', sa.String(length=20), nullable=True),
    sa.Column('hit_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('last_computed', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('market_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id_a', sa.Integer(), nullable=False),
    sa.Column('market_id_b', sa.Integer(), nullable=False),
    sa.Column('similarity_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['market_id_a'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['market_id_b'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('watch_type', sa.String(length=50), nullable=False),
    sa.Column('watch_value', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts_sent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('bet_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bet_id'], ['bets.id'], ),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anomaly_scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cross_platform_corroboration', sa.Numeric(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('confidence_tier', sa.String(length=20), nullable=True))

    with op.batch_alter_table('trader_baselines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('large_bet_win_rate', sa.Numeric(precision=5, scale=4), nullable=True))
        batch_op.add_column(sa.Column('reputation_score', sa.Numeric(precision=5, scale=4), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trader_baselines', schema=None) as batch_op:
        batch_op.drop_column('reputation_score')
        batch_op.drop_column('large_bet_win_rate')

    with op.batch_alter_table('anomaly_scores', schema=None) as batch_op:
        batch_op.drop_column('confidence_tier')
        batch_op.drop_column('cross_platform_corroboration')

    op.drop_table('alerts_sent')
    op.drop_table('watchlists')
    op.drop_table('market_matches')
    op.drop_table('users')
    op.drop_table('calibration_summary')
    # ### end Alembic commands ###
