"""Initial schema

Revision ID: 7d5477527d5e
Revises: 
Create Date: 2026-07-07 22:48:43.046950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d5477527d5e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('external_market_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('open_date', sa.DateTime(), nullable=True),
    sa.Column('resolution_date', sa.DateTime(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_outcome', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'external_market_id', name='uq_market_platform_id')
    )
    op.create_table('traders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('external_trader_id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'external_trader_id', name='uq_trader_platform_id')
    )
    op.create_table('bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('trader_id', sa.Integer(), nullable=True),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('size', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('price', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('bet_timestamp', sa.DateTime(), nullable=False),
    sa.Column('time_to_resolution_hours', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_baselines',
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('median_bet_size', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('mad_bet_size', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('last_computed', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('market_id')
    )
    op.create_table('trader_baselines',
    sa.Column('trader_id', sa.Integer(), nullable=False),
    sa.Column('median_bet_size', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('mad_bet_size', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('total_resolved_bets', sa.Integer(), nullable=False),
    sa.Column('last_computed', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], ),
    sa.PrimaryKeyConstraint('trader_id')
    )
    op.create_table('anomaly_scores',
    sa.Column('bet_id', sa.Integer(), nullable=False),
    sa.Column('self_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('market_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('lifecycle_weight', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('composite_score', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('scoring_mode', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['bet_id'], ['bets.id'], ),
    sa.PrimaryKeyConstraint('bet_id')
    )
    op.create_table('calibration_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bet_id', sa.Integer(), nullable=False),
    sa.Column('predicted_side', sa.String(length=10), nullable=False),
    sa.Column('actual_outcome', sa.String(length=10), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bet_id'], ['bets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bet_id', sa.Integer(), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('relevance_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('sentiment_label', sa.String(length=20), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('event_category', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['bet_id'], ['bets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_events')
    op.drop_table('calibration_results')
    op.drop_table('anomaly_scores')
    op.drop_table('trader_baselines')
    op.drop_table('market_baselines')
    op.drop_table('bets')
    op.drop_table('traders')
    op.drop_table('markets')
    # ### end Alembic commands ###
